//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS3DB.Pages
{
    public partial class UsageDetails
    {
        protected global::System.Web.UI.WebControls.TextBox txtMobileNumber;
        protected global::System.Web.UI.WebControls.Button btnFetchUsage;
        protected global::System.Web.UI.WebControls.Repeater usageDetailsRepeater;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
